name: ARM64 Cross-Compile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabi
          arm-linux-gnueabi-gcc -O2 -marm ptbl.c -ldl -o ptbl -Wl,--export-dynamic
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: arm64-binaries
          path: ptbl
