name: ARM64 Cross-Compile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install ARM64 toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu

    - name: Compile for ARM64
      run: |
        aarch64-linux-gnu-gcc -O2 ptbl.c -ldl -o ptbl_arm64 -Wl,--export-dynamic
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: arm64-binaries
        path: ptbl_arm64
