name: ARM64 Cross-Compile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04-arm64  # 或 windows-11-arm
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: gcc -O2 ptbl.c -ldl -static -o ptbl_arm64 -Wl,--export-dynamic
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: arm64-binaries
          path: ptbl_arm64
